---
- hosts: nextcloud
  become_user: "{{pac}}-{{user}}"

  roles:
  - role: ../roles/systemd_user
  - role: ../roles/logrotate
  - role: ../roles/redis


  tasks:
  #################################
  ## create directories
  #################################
  - name: create directory nextcloud
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      state: directory
  - name: create directory bin
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/bin"
      state: directory

  ##################################
  ## install nextcloud
  ##################################
  - name: install nextcloud
    become: yes
    unarchive:
      src: https://download.nextcloud.com/server/releases/nextcloud-{{nextcloud.version}}.tar.bz2
      remote_src: yes
      dest: "{{userhome}}/nextcloud"
      extra_opts: [--strip-components=1]
      creates: "{{userhome}}/nextcloud/config"

  #################################
  ## setup the data directory
  #################################
  - name: create data directory
    become: yes
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
      recurse: no

  - name: configure data directory path
    become: yes
    set_fact:
      data_path: "/home/pacs/{{pac}}/users/{{user}}/data"

  ##################################
  ## other software configuration
  ##################################

  - name: upload logrotate configuration
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/.logrotate" src="templates/logrotate" mode=0600

  ########################################
  ## finish installation and install apps
  ########################################
  - name: finish nextcloud installation
    become: yes
    shell: |
      # see https://docs.nextcloud.com/server/latest/admin_manual/installation/command_line_installation.html
      php occ maintenance:install --database "mysql" --database-name "{{pac}}_{{dbname}}" --database-user "{{pac}}_{{dbuser}}" --database-pass "{{dbpassword}}" --admin-user "{{nextcloud.adminuser}}" --admin-pass "{{nextcloud.adminpassword}}" --data-dir "{{data_path}}"
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      creates: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php"

  - name: install default apps
    become: yes
    shell: |
      # see https://docs.nextcloud.com/server/19/admin_manual/configuration_server/occ_command.html#apps-commands-label
      php -d memory_limit=512M ./occ app:install {{item}}
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      creates: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/apps/{{item}}"
    loop: "{{ ['contacts', 'calendar', 'mail', 'spreed', 'groupfolders', 'twofactor_totp'] }}"

  ##########################
  ## nextcloud configuration
  ##########################
  - name: set the trusted domain
    become: yes
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*0 => 'localhost',$"
      line: "    0 => 'localhost', 1 => '{{domain}}',"

  - name: configure default_phone_region
    become: yes
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*'default_phone_region' =>.*,$"
      line: "  'default_phone_region' => '{{nextcloud.default_phone_region}}',"
      insertbefore: '^\)\;'
    when: nextcloud.default_phone_region is defined

  - name: configure skeletondirectory
    become: yes
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*'skeletondirectory' =>.*,$"
      line: "  'skeletondirectory' => '',"
      insertbefore: '^\)\;'
    when: nextcloud.empty_skeleton_directory is defined and nextcloud.empty_skeleton_directory == True

  - name: configure updater.server.url
    become: yes
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*'updater.server.url' =>.*,$"
      line: "  'updater.server.url' => '{{nextcloud.updater_server_url}}',"
      insertbefore: '^\)\;'
    when: nextcloud.updater_server_url is defined

  - name: configure data directory
    become: yes
    lineinfile:
      path: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php"
      regexp: "^.*'datadirectory' => '.*',$"
      line: "  'datadirectory' => '/home/pacs/{{pac}}/users/{{user}}/data',"

  - name: Database Optimisations
    become: yes
    shell: |
      source ~/.profile
      php occ db:add-missing-primary-keys --no-interaction || exit -1
      php occ db:add-missing-columns --no-interaction || exit -1
      php occ db:add-missing-indices --no-interaction | exit -1
      php occ db:convert-filecache-bigint --no-interaction || exit -1
      php occ maintenance:repair --include-expensive || echo "ignoring a problem"
    args:
      executable: /bin/bash
      chdir: "{{userhome}}/nextcloud"

  ########################
  ## setup the apache site
  ########################
  - name: Check for htdocs-ssl directory
    become: yes
    stat:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
    register: htdocsssl
  - name: drop htdocs-ssl
    become: yes
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent
    when: htdocsssl.stat.exists and htdocsssl.stat.isdir
  - name: create symbolic link for htdocs-ssl
    become: yes
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link

  ######################
  ## upload backup script
  ######################
  - name: upload database backup script
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin/backup.sh" src="templates/backup.sh" mode=0700

  ####################################
  ## install cron jobs
  ####################################
  - name: run logrotate once a day
    become: yes
    cron:
      name: "logrotate"
      minute: "27"
      hour: "1"
      job: "/usr/sbin/logrotate -s $HOME/.logrotate.state $HOME/.logrotate"
  - name: run nextcloud cronjob
    become: yes
    cron:
      name: "nextcloud"
      minute: "*/5"
      job: "/usr/bin/php $HOME/nextcloud/cron.php"
  - name: update all nextcloud apps each night
    become: yes
    cron:
      name: "nextcloud app updates"
      hour: "1"
      minute: "12"
      job: "/usr/bin/php $HOME/nextcloud/occ app:update --all -n --no-ansi"
  - name: backup the database
    become: yes
    cron:
      name: "database backup"
      hour: "1"
      minute: "23"
      job: "$HOME/bin/backup.sh"

  - name: upload nextcloud update script
    become: yes
    template: dest="/home/pacs/{{pac}}/users/{{user}}/bin/update.sh" src="templates/update.sh" mode=0700
    when: nextcloud.updater_server_url is defined
